### ISSUE TITLE
没有.emacs.d是什么鬼

### ISSUE THREAD

**Issue by reverland** [d0u9/.dot#1]
233

**Comment by d0u9** [comment]
最近换回neovim了，手太小。emacs每次让手特别的累。。。

如果对emacs感兴趣的话，戳这里[https://github.com/d0u9/.emacs.d](https://github.com/d0u9/.emacs.d)

如果对nvim感兴趣的话 戳这个[http://www.d0u9.xyz/neovim-pei-zhi-yu-cha-jian-shuo-ming/](http://www.d0u9.xyz/neovim-pei-zhi-yu-cha-jian-shuo-ming/)
